//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assigned
    {
        public int mentorid { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> startday { get; set; }
        public Nullable<System.DateTime> endday { get; set; }
        public string address { get; set; }
        public string courseid { get; set; }
    
        public virtual course course { get; set; }
        public virtual mentor mentor { get; set; }
    }
}
