//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public course()
        {
            this.assigneds = new HashSet<assigned>();
        }
    
        public string courseid { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string time { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public int trainee_course { get; set; }
        public Nullable<int> idskill { get; set; }
        public int isnotification { get; set; }
        public string image_course { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assigned> assigneds { get; set; }
        public virtual skill skill { get; set; }
        public virtual trainee trainee { get; set; }
    }
}
